---
startup_config:
  
  -
    slave_name: "somanet_node_1"
    sdo_index: 0x6098
    sdo_subindex: 0x0
    data_type: int8
    data_value: 0x25

  -
    slave_name: "somanet_node_1"
    sdo_index: 0x6060
    sdo_subindex: 0x0
    data_type: uint8
    data_value: 0x6
  -
    slave_name: "somanet_node_1"
    sdo_index: 0x6040
    sdo_subindex: 0x0
    data_type: uint16
    data_value: 0x10

  -
    slave_name: "somanet_node_2"
    sdo_index: 0x6098
    sdo_subindex: 0x0
    data_type: int8
    data_value: 0x25

  -
    slave_name: "somanet_node_2"
    sdo_index: 0x6060
    sdo_subindex: 0x0
    data_type: uint8
    data_value: 0x6
  -
    slave_name: "somanet_node_2"
    sdo_index: 0x6040
    sdo_subindex: 0x0
    data_type: uint16
    data_value: 0x10

...

---
controller_config:

  domain_names:
    - domain_0
  log_directory_path: "/home/naci/Projects/igh_master/logs/"
  cycle_period: 500
...

# Configuration for the SICK Safety PLC
# ---

# slave_name: safety_plc
# slave_type: PLC
# num_of_slaves: 1
# domain_name: domain_0
# vendor_id: 0x01000056
# product_id: 0x00002301
# slave_position: 0
# slave_alias: 0

# pdo_names:
#   - "output_data"
#   - "diag"
#   - "input_data"

# pdo_types:
#   - int8[]
#   - uint8
#   - int8[]

# pdo_entry_info:
#   indexes:
#     - 0x2001
#     - 0x10F3
#     - 0x2000
#   subindexes:
#     - 0x01
#     - 0x04
#     - 0x01

#   bit_lengths:
#     - 80
#     - 8
#     - 80

#   use_default_pdo_mapping: true 
#   rxpdo_address: 0x1600
#   txpdo_address: 0x1a00
#   rxpdo_indexes:
#    - 0x1600
#   rxpdo_size: 1
#   txpdo_indexes:
#     - 0x1a00
#   txpdo_size: 2
# slave_sync_info:
#   num_sync_managers: 4
#   sync_manager_directions:
#     - output
#     - input
#     - output
#     - input
#   number_of_pdos:
#     - 0
#     - 0
#     - 1
#     - 1
#   pdo_index_diff:
#     - "NULL"
#     - "NULL"
#     - 0
#     - 1
#   watchdog_mode:
#     - disable
#     - disable
#     - enable
#     - disable

# ...

#Configuration for the Somanet Node Safety Motor Drivers
---
slave_name: "somanet_node"
slave_type: "driver"
num_of_slaves: 3
domain_name: "domain_0"
vendor_id: 0x000022d2
product_id: 0x00000201
slave_position: 1
slave_alias: 0
pdo_names:
  - "ctrl_word"
  - "op_mode"
  - "target_position"
  - "target_velocity"
  - "homing_method"
  - "homing_speed"
  - "homing_speed2"
  - "homing_accel"
  - "status_word"
  - "actual_position"
  - "actual_velocity"
  - "error_code"
  - "op_mode_display"
pdo_types:
  - uint16
  - uint8
  - int32
  - int32
  - int8
  - uint32
  - uint32
  - uint32
  - uint16
  - int32
  - int32
  - uint16
  - int8
pdo_entry_info:
  indexes:
    - 0x6040
    - 0x6060
    - 0x607A
    - 0x60ff
    - 0x6098
    - 0x6099
    - 0x6099
    - 0x609A
    - 0x6041
    - 0x6064
    - 0x606c
    - 0x603F
    - 0x6061
  subindexes:
    - 0x00
    - 0x00
    - 0x00
    - 0x00
    - 0x00
    - 0x01
    - 0x02
    - 0x00
    - 0x00
    - 0x00
    - 0x00
    - 0x00
    - 0x00
  bit_lengths:
    - 16
    - 8
    - 32
    - 32
    - 8
    - 32
    - 32
    - 32
    - 16
    - 32
    - 32
    - 16
    - 8
  use_default_pdo_mapping: false
  rxpdo_address: 0x1600
  txpdo_address: 0x1A00
  rxpdo_indexes:
   - 0x1600
  rxpdo_size: 8
  txpdo_indexes:
    - 0x1A00
  txpdo_size: 5
slave_sync_info:
  num_sync_managers: 4
  sync_manager_directions:
    - output
    - input
    - output
    - input
  number_of_pdos:
    - 0
    - 0
    - 1
    - 1
  pdo_index_diff:
    - "NULL"
    - "NULL"
    - 0
    - 1
  watchdog_mode:
    - disable
    - disable
    - enable
    - disable
dc_info:
  assign_activate: 0x0300
  sync0_cycle: 2000000
  sync0_shift: 1000000
  sync1_cycle: 2000000
  sync1_shift: 0

...