hamal:
  hardware_interface:
    left_wheel: left_wheel_joint
    right_wheel: right_wheel_joint
    lifter_joint: lifter_joint
    lifter_control_type: velocity
    loop_hz: 500.0
    ethercat_config_path: /home/rnd/hamal_ws/src/hamal_hardware/config/hamal_config.yaml
    #lifter_joint: lifter_joint
    lifter_interface_type: velocity
    max_vel: 3000
    min_vel: -3000
    max_acc: 1000
    min_acc: -1000
    
    reduction: 24.685
    #position_increment: 20480.0
    position_increment: 16384.0

    lifter_reduction: 1.0
    lifter_position_increment: 4096.0

  lifter_hardware_interface:
    lifter_joint: lifter_joint
    ethercat_config_path: /home/grass/amr_ws/src/hamal_hardware/config/lifter_config.yaml
    loop_hz: 50.0
    reduction: 24.685
    position_increment: 20480.0
    max_position: 1.0
    max_velocity: 6.0
    max_accel: 12.0
    pid:
      Kp: 0.1
      Ki: 0.01
      Kd: 0.0