---
startup_config:

...
---
controller_config:

  domain_names:
    - lifter_domain
  log_directory_path: "/home/naci/Projects/igh_master/logs/"
  cycle_period: 500
...
---
slave_name: "somanet_node"
slave_type: "driver"
num_of_slaves: 1
domain_name: "lifter_domain"
vendor_id: 0x000022d2
product_id: 0x00000201
slave_position: 0
slave_alias: 0
pdo_names:
  - "ctrl_word"
  - "op_mode"
  - "target_position"
  - "target_velocity"
  - "homing_method"
  - "homing_speed"
  - "homing_speed2"
  - "homing_accel"
  - "status_word"
  - "actual_position"
  - "actual_velocity"
  - "error_code"
  - "op_mode_display"
pdo_types:
  - uint16
  - uint8
  - int32
  - int32
  - int8
  - uint32
  - uint32
  - uint32
  - uint16
  - int32
  - int32
  - uint16
  - int8
pdo_entry_info:
  indexes:
    - 0x6040
    - 0x6060
    - 0x607A
    - 0x60ff
    - 0x6098
    - 0x6099
    - 0x6099
    - 0x609A
    - 0x6041
    - 0x6064
    - 0x606c
    - 0x603F
    - 0x6061
  subindexes:
    - 0x00
    - 0x00
    - 0x00
    - 0x00
    - 0x00
    - 0x01
    - 0x02
    - 0x00
    - 0x00
    - 0x00
    - 0x00
    - 0x00
    - 0x00
  bit_lengths:
    - 16
    - 8
    - 32
    - 32
    - 8
    - 32
    - 32
    - 32
    - 16
    - 32
    - 32
    - 16
    - 8
  use_default_pdo_mapping: false
  rxpdo_address: 0x1600
  txpdo_address: 0x1A00
  rxpdo_indexes:
   - 0x1600
  rxpdo_size: 8
  txpdo_indexes:
    - 0x1A00
  txpdo_size: 5
slave_sync_info:
  num_sync_managers: 4
  sync_manager_directions:
    - output
    - input
    - output
    - input
  number_of_pdos:
    - 0
    - 0
    - 1
    - 1
  pdo_index_diff:
    - "NULL"
    - "NULL"
    - 0
    - 1
  watchdog_mode:
    - disable
    - disable
    - enable
    - disable
dc_info:
  assign_activate: 0x0300
  sync0_cycle: 2000000
  sync0_shift: 1000000
  sync1_cycle: 2000000
  sync1_shift: 0

...