TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.36
  min_vel_x: -0.36

  max_vel_theta:  0.48
  min_vel_theta: -0.48
  min_in_place_vel_theta: 0.24

  acc_lim_x: 2.0
  acc_lim_y: 2.0
  acc_lim_theta: 2.0

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.05

# Differential-drive robot configuration
  holonomic_robot: false

# Forward Simulation Parameters
  sim_time: 1.7
  vx_samples: 3
  vtheta_samples: 20
  sim_granularity: 0.025
