
#footprint: [[-0.410, -0.305], [-0.410, 0.305], [0.410, 0.305], [0.410, -0.305]]
footprint: [[-1,-0.55],[-1,0.55],[1,0.55],[1,-0.55]]
#robot_radius: 0.105

obstacle_range: 2.5
max_obstacle_height: 2.0
raytrace_range: 3.0
inflation_radius: 0.55
cost_scaling_factor: 10.0

map_type: costmap
observation_sources: scan
scan: {sensor_frame: base_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}
