footprint: [[-1,-0.55],[-1,0.55],[1,0.55],[1,-0.55]]

obstacle_range: 2.5
#max_obstacle_height: 2.0
raytrace_range: 3.0
#inflation_radius: 0.55

map_type: costmap
#observation_sources: scan
#scan: {sensor_frame: base_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

#static_layer:
#    map_topic: /map
#    subscribe_to_updates: true

obstacles_layer:
  observation_sources: scan
  scan: {sensor_frame: base_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true, obstacle_range: 3.5, raytrace_range: 3.0 , expected_update_rate: 12.5}
  track_unknown_space: true
  
inflater_layer:
 #inflation_radius: 1.75
 #cost_scaling_factor: 2.58
 inflation_radius: 1.5    
 cost_scaling_factor: 3.0
 track_unknown_space: true


observation_persistence: 0.0