footprint: [[-1,-0.55],[-1,0.55],[1,0.55],[1,-0.55]]

obstacle_range: 3.5
#max_obstacle_height: 2.0
raytrace_range: 3.0
#inflation_radius: 0.55

map_type: costmap
#observation_sources: scan
#scan: {sensor_frame: base_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
plugins:
- {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
- {name: inflater_layer, type: "costmap_2d::InflationLayer"}

obstacles_layer:
  observation_sources: scan
  scan: {sensor_frame: base_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true, obstacle_range: 3.5, raytrace_range: 3.0 , expected_update_rate: 12.5}
  track_unknown_space: true
  
inflater_layer:
 #inflation_radius: 1.75
 #cost_scaling_factor: 2.58
 inflation_radius: 1.0
 cost_scaling_factor: 1.5
 track_unknown_space: true