# DWAPlannerROS:
  
#   #acc_lim_th: 0.5
#   #acc_lim_x: 0.35
#   #acc_lim_th: 0.35
#   #acc_lim_x: 0.5
#   #acc_lim_y: 0.0

#   acc_lim_th: 0.35
#   acc_lim_x: 0.5
#   acc_lim_y: 0.0

#   max_vel_x: 0.9
#   min_vel_x: -0.9

#   max_vel_y: 0.0
#   min_vel_y: -0.0

#   max_vel_trans: 0.9
#   min_vel_trans: 0.01

#   max_vel_theta: 0.7
#   min_vel_theta: 0.01 

#   sim_time: 4.0
#   sim_granularity: 0.05

#   goal_distance_bias: 20.0
#   path_distance_bias: 32.0
#   occdist_scale: 0.02

#   stop_time_buffer: 0.2
#   oscillation_reset_dist: 0.05
#   #oscillation_reset_angle: 0.0001

#   forward_point_distance: 0.325

#   scaling_speed: 0.25
#   max_scaling_factor: 0.2

#   vx_samples: 20
#   vy_samples: 0
#   vtheta_samples: 40

#   sim_period: 0.1

#   xy_goal_tolerance: 0.2
#   yaw_goal_tolerance: 0.1
#   latch_xy_goal_tolerance: true

#   theta_stopped_vel: 0.01
#   trans_stopped_vel: 0.01
#   controller_frequency: 50.0
DWAPlannerROS:
  
  #acc_lim_th: 0.5
  #acc_lim_x: 0.35
  #acc_lim_th: 0.35
  #acc_lim_x: 0.5
  #acc_lim_y: 0.0

  acc_lim_theta: 0.375
  acc_lim_trans: 0.25
  acc_lim_x: 0.5
  acc_lim_y: 0.0

  max_vel_x: 0.5
  min_vel_x: -0.5

  max_vel_y: 0.0
  min_vel_y: -0.0

  max_vel_trans: 0.5
  min_vel_trans: 0.1

  max_vel_theta: 0.5
  min_vel_theta: 0.01 

  sim_time: 2.5
  sim_granularity: 0.05

  goal_distance_bias: 24.0
  path_distance_bias: 32.0
  occdist_scale: 0.02

  stop_time_buffer: 0.2
  oscillation_reset_dist: 0.05

  forward_point_distance: 0.31

  scaling_speed: 0.25
  max_scaling_factor: 0.2

  vx_samples: 30
  vy_samples: 0
  vth_samples: 40

  sim_period: 0.1

  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false

  theta_stopped_vel: 0.001
  trans_stopped_vel: 0.001
  #controller_frequency: 20.0