DWAPlannerROS:
  
  #acc_lim_th: 0.5
  #acc_lim_x: 0.35
  acc_lim_th: 1.0
  acc_lim_x: 2.5
  acc_lim_y: 0.0

  max_vel_x: 0.65
  min_vel_x: -0.65

  max_vel_y: 0.0
  min_vel_y: -0.0

  max_trans_vel: 0.65
  min_trans_vel: 0.1

  max_rot_vel: 1.0
  min_rot_vel: 0.1

  sim_time: 4.0
  sim_granularity: 0.05

  goal_distance_bias: 32.0
  path_distance_bias: 24.0
  occdist_scale: 0.01

  stop_time_buffer: 0.2
  oscillation_reset_dist: 0.05

  forward_point_distance: 0.325

  scaling_speed: 0.25
  max_scaling_factor: 0.2

  vx_samples: 20
  vy_samples: 0
  vtheta_samples: 40

  sim_period: 0.1

  xy_goal_tolerance: 0.01
  yaw_goal_tolerance: 0.17

  rot_stopped_vel: 0.01
  trans_stopped_vel: 0.01
