GlobalPlanner:
  allow_unknown: false
  default_tolerance: 0.0
  visualize_potential: false
  use_dijkstra: true
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false
  lethal_cost: 255
  neutral_cost: 50
  cost_factor: 3
  publish_potential: true
  orientation_mode: 2
  orientation_window_size: 1
  outline_map: true
