local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint

  update_frequency: 50.0
  publish_frequency: 50.0
  transform_tolerance: 0.5 
  track_unknown_space: false

  static_map: false  
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05
  
