local_costmap:
  global_frame: map
  robot_base_frame: base_footprint

  update_frequency:  10.0
  publish_frequency: 5.0
  transform_tolerance: 0.5 
  track_unknown_space: false

  static_map: false  
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.05
  
