local_costmap:
  global_frame: odom
  robot_base_frame: base_link

  update_frequency:  20.0
  publish_frequency: 10.0
  transform_tolerance: 0.5 
  plugins:
    - {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflater_layer, type: "costmap_2d::InflationLayer"}

  static_map: false  
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.05
  inf_is_valid: true
  track_unknown_space: false

  
