hamal:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100 

  mobile_base_controller:
    type        : diff_drive_controller/DiffDriveController
    left_wheel  : 'left_wheel_joint'
    right_wheel : 'right_wheel_joint'
    publish_rate: 100               # default: 50
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    #pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    #twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    
    allow_multiple_cmd_vel_publishers: true
    odom_frame_id: odom
    base_frame_id: base_footprint
    # Wheel separation and diameter. These are both optional.
    # diff_drive_controller will attempt to read either one or both from the
    # URDF if not specified as a parameter
    wheel_separation : 0.457
    wheel_radius : 0.105
    publish_cmd : false

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0 # default: 1.0
    wheel_radius_multiplier    : 1.0 # default: 1.0
 
    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 0.5
 
    # Base frame_id #default: base_link

    open_loop: false
    enable_odom_tf: false
 
    # Velocity and acceleration limitss
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 2.0  # m/s
        min_velocity           : -2.0 # m/s
        has_acceleration_limits: true
        max_acceleration       : 0.5 # m/s^2
        min_acceleration       : -0.5 # m/s^2
        has_jerk_limits        : false
        max_jerk               : 1.0  # m/s^3
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 3.0 # rad/s
        has_acceleration_limits: true
        max_acceleration       : 0.98  # rad/s^2
        has_jerk_limits        : false
        max_jerk               : 3.92 # rad/s^3

  lifter_controller:
    type: hamal_lifter_controller/HamalLifterController
    lifter_joint_name: "lifter_joint"
    controller_rate: 50.0
    max_position: 1.0
    max_velocity: 3.0
    max_accel: 6.0
    tolerance: 0.05


  # diff_drive_controller:
  #  type: hamal_diff_drive_controller/HamalDiffDriveController
   
  #  left_wheel: left_wheel_joint
   
  #  right_wheel: right_wheel_joint

  #  publish_rate: 50.0

  #  velocity_rolling_window_size: 10
 
  #  wheel_radius: 0.210

  #  wheel_separation: 0.457

  #  use_position_for_odom: true

  #  use_velocity_for_odom: true

  #  odom_tf_enabled: false # Leave the tf publishing to EKF for now

  #  base_frame_id: base_link

  #  odom_frame_id: odom

  #  pose_covariance: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]

  #  twist_covariance: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]

  #  twist_command_timeout: 0.5
   
  #  twist_cmd_topic_name: "cmd_vel"

  #  limiter:
  #    linear_x:
  #      has_velocity_limits: true
  #      has_accel_limits: true
  #      has_jerk_limits: false

  #      max_vel: 0.45
  #      min_vel: -0.45

  #      max_accel: 0.225
  #      min_accel: -0.225

  #      max_jerk: 1.0
  #      min_jerk: -1.0

  #    angular_z:
  #      has_velocity_limits: true
  #      has_accel_limits: true
  #      has_jerk_limits: false

  #      max_vel: 1.96
  #      min_vel: -1.96

  #      max_accel: 0.98
  #      min_accel: -0.98

  #      max_jerk: 3.92
  #      min_jerk: -3.92
