profile_controller_params:
  trapezoidal_profile:
    velocity_controller:
      kp: 0.0
      ki: 0.0
      kd: 0.0
    orientation_controller:
      kp: 1.0
      ki: 0.0
      kd: 0.0
    linear_position_controller:
      kp: 0.2
      ki: 0.035
      kd: 0.0